### ISSUE TITLE
Criação do Footer

### ISSUE THREAD

**Issue by Tatu-Armadillo** [Tatu-Armadillo/club-travel-front#3]
1 dia

**Comment by Tatu-Armadillo** [comment]
Criação do footer com botão de acesso as redes sociais, contatos (email e whatsapp), nome do dominio



![Image](https://user-images.githubusercontent.com/69278300/211565306-2bd3eb90-d63a-4f3f-9482-5521e31dbb24.png)

**Comment by joaoygorr** [comment]
Done
