### ISSUE TITLE
Tela de cadastro

### ISSUE THREAD

**Issue by Tatu-Armadillo** [Tatu-Armadillo/club-travel-front#6]
2 dias

**Comment by Tatu-Armadillo** [comment]
Criar formulario para cadastro
Nome Completo, Email, Numero de contato, Imagem de perfil (Não obrigatorio)

**Comment by mCszao** [comment]
+3 dias para conclusão

**Comment by Tatu-Armadillo** [comment]
Exemplo 

![Image](https://user-images.githubusercontent.com/69278300/212782814-302820aa-5d42-42c8-85c5-fbaae0321f17.png)
